workspace = { }

[package]
name = "tauri-cli"
version = "1.0.0-beta.7"
authors = [ "Tauri Programme within The Commons Conservancy" ]
edition = "2018"
categories = [ "gui", "web-programming" ]
license = "Apache-2.0 OR MIT"
homepage = "https://tauri.studio"
repository = "https://github.com/tauri-apps/tauri"
description = "Command line interface for building Tauri apps"
include = [ "src/", "/templates", "MergeModules/", "*.json", "*.rs" ]

[[bin]]
name = "cargo-tauri"
path = "src/main.rs"

[dependencies]
clap = { version = "3.0.0-beta.4", features = [ "yaml" ] }
anyhow = "1.0"
tauri-bundler = { version = "1.0.0-beta.4", path = "../bundler" }
colored = "2.0"
once_cell = "1.8"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
serde_with = "1.9"
notify = "4.0"
shared_child = "0.3"
toml_edit = "0.2"
json-patch = "0.2"
schemars = "0.8"
toml = "0.5"
valico = "3.6"
handlebars = "4.1"
include_dir = "0.6"
minisign = "0.6"
base64 = "0.13.0"
ureq = "2.2"
os_info = "3.0"
semver = "1.0"
regex = "1.5"
lazy_static = "1"
libc = "0.2"
terminal_size = "0.1"
unicode-width = "0.1"
tempfile = "3"
zeroize = "1.4"

[target."cfg(windows)".dependencies]
webview2-com-sys = { path = "../../../webview2-rs/crates/bindings" }
windows = "0.19.0"
encode_unicode = "0.3"

[target."cfg(target_os = \"linux\")".dependencies]
heck = "0.3"

[target."cfg(target_os = \"linux\")".build-dependencies]
heck = "0.3"

[build-dependencies]
schemars = "0.8"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
serde_with = "1.9"
