[package]
name = "tauri"
version = "1.0.0-beta.9"
authors = [ "Tauri Programme within The Commons Conservancy" ]
categories = [ "gui", "web-programming" ]
license = "Apache-2.0 OR MIT"
homepage = "https://tauri.studio"
repository = "https://github.com/tauri-apps/tauri"
description = "Make tiny, secure apps for all desktop platforms with Tauri"
edition = "2018"
exclude = [
  "/test",
  "/.scripts",
  ".license_template",
  "CHANGELOG.md",
  "/target"
]
readme = "README.md"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [ "--cfg", "doc_cfg" ]
default-target = "x86_64-unknown-linux-gnu"
targets = [
  "x86_64-pc-windows-msvc",
  "x86_64-unknown-linux-gnu",
  "x86_64-apple-darwin"
]

[package.metadata.cargo-udeps.ignore]
normal = [ "attohttpc" ]

[dependencies]
serde_json = { version = "1.0", features = [ "raw_value" ] }
serde = { version = "1.0", features = [ "derive" ] }
tokio = { version = "1.9", features = [ "rt", "rt-multi-thread", "sync", "fs", "io-util" ] }
futures = "0.3"
uuid = { version = "0.8", features = [ "v4" ] }
url = { version = "2.2" }
thiserror = "1.0"
once_cell = "1.8"
tauri-runtime = { version = "0.2.1", path = "../tauri-runtime" }
tauri-macros = { version = "1.0.0-beta.5", path = "../tauri-macros" }
tauri-utils = { version = "1.0.0-beta.3", path = "../tauri-utils" }
tauri-runtime-wry = { version = "0.2.1", path = "../tauri-runtime-wry", optional = true }
rand = "0.8"
tempfile = "3"
semver = "1.0"
serde_repr = "0.1"
zip = "0.5"
ignore = "0.4"
either = "1.6"
tar = "0.4"
flate2 = "1.0"
http = "0.2"
state = "0.5"
bincode = "1.3"
dirs-next = "2.0"
percent-encoding = "2.1"
base64 = { version = "0.13", optional = true }
clap = { version = "=3.0.0-beta.2", optional = true }
notify-rust = { version = "4.5", optional = true }
reqwest = { version = "0.11", features = [ "json", "multipart" ], optional = true }
bytes = { version = "1", features = [ "serde" ], optional = true }
attohttpc = { version = "0.17", features = [ "json", "form" ] }
open = { version = "2.0", optional = true }
shared_child = { version = "0.3", optional = true }
os_pipe = { version = "0.9", optional = true }
rfd = { version = "0.4.3", features = [ "parent" ] }
raw-window-handle = "0.3.3"
minisign-verify = { version = "0.1", optional = true }
os_info = { version = "3.0.6", optional = true }
futures-lite = "1.12"

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
gtk = { version = "0.14", features = [ "v3_20" ] }
glib = "0.14"

[target."cfg(target_os = \"macos\")".dependencies]
embed_plist = "1.2"

[build-dependencies]
cfg_aliases = "0.1.1"

[dev-dependencies]
proptest = "1.0.0"
serde_json = "1.0"
tauri = { path = "." }
serde = { version = "1.0", features = [ "derive" ] }
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
tokio-test = "0.4.2"
tokio = { version = "1.9", features = [ "full" ] }
mockito = "0.30"

[features]
default = [ "wry" ]
dox = [ "tauri-runtime-wry/dox" ]
wry = [ "tauri-runtime-wry" ]
cli = [ "clap" ]
custom-protocol = [ "tauri-macros/custom-protocol" ]
api-all = [
  "notification-all",
  "global-shortcut-all",
  "shell-all",
  "os-all",
  "dialog-all",
  "updater",
  "path-all"
]
updater = [ "minisign-verify", "base64" ]
system-tray = [ "tauri-runtime/system-tray", "tauri-runtime-wry/system-tray" ]
reqwest-client = [ "reqwest", "bytes" ]
fs-all = [ "fs-write-binary-file" ]
fs-read-text-file = [ ]
fs-read-binary-file = [ ]
fs-write-file = [ ]
fs-write-binary-file = [ "base64" ]
fs-read-dir = [ ]
fs-copy-file = [ ]
fs-create-dir = [ ]
fs-remove-dir = [ ]
fs-remove-file = [ ]
fs-rename-file = [ ]
path-all = [ ]
window-all = [ ]
window-create = [ ]
shell-all = [ "shell-open", "shell-execute" ]
shell-execute = [ "shared_child", "os_pipe" ]
shell-open = [ "open" ]
dialog-all = [ "dialog-open", "dialog-save" ]
dialog-open = [ ]
dialog-save = [ ]
http-all = [ ]
http-request = [ ]
notification-all = [ "notify-rust" ]
global-shortcut-all = [ ]
os-all = [ "os_info" ]

[[example]]
name = "commands"
path = "../../examples/commands/src-tauri/src/main.rs"

[[example]]
name = "helloworld"
path = "../../examples/helloworld/src-tauri/src/main.rs"

[[example]]
name = "multiwindow"
path = "../../examples/multiwindow/src-tauri/src/main.rs"

[[example]]
name = "navigation"
path = "../../examples/navigation/src-tauri/src/main.rs"

[[example]]
name = "splashscreen"
path = "../../examples/splashscreen/src-tauri/src/main.rs"

[[example]]
name = "state"
path = "../../examples/state/src-tauri/src/main.rs"

[[example]]
name = "resources"
path = "../../examples/resources/src-tauri/src/main.rs"

[[example]]
name = "streaming"
path = "../../examples/streaming/src-tauri/src/main.rs"
